on:
  push:
    branches:
      - main
    paths:
      - '**.qmd'
      - '**.R'
  schedule:
      - cron: "03 04,16 * * *"
  workflow_dispatch:

name: build-dash

permissions:
  contents: write

jobs:
  build-dash:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      RENV_PATHS_ROOT: ~/.local/share/renv
    steps:

    - uses: actions/checkout@v3

    - name: Set up Quarto
      uses: quarto-dev/quarto-actions/setup@v2
      with:
        version: pre-release

    - uses: r-lib/actions/setup-r@v2

    - name: Add Ubuntu dependencies
      run: sudo apt-get install libglpk40

    - uses: r-lib/actions/setup-renv@v2

    - name: Cache targets data
      uses: actions/cache@v3
      with:
          path: _targets
          key: ${{ runner.os }}-targets-v1-${{ hashFiles('**/cache.log') }}
          restore-keys: |
              ${{ runner.os }}-targets-v1-

    - name: Build Pipeline and Dashboard
      run: Rscript -e 'targets::tar_make()'
      env:
        CALDAV_URL: ${{ secrets.CALDAV_URL }}
        NEXTCLOUD_USER: ${{ secrets.NEXTCLOUD_USER }}
        NEXTCLOUD_PASSWORD: ${{ secrets.NEXTCLOUD_PASSWORD }}

